server:
  port: 80
  forward-headers-strategy: native
spring:
  datasource:
    username: bup
    password: 
    #      url: jdbc:mysql://127.0.0.1:3306/answer?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    url: jdbc:mysql:///bup?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  task:
    scheduling:
      pool:
        size: 10
#  h2:
#    console:
#      enabled: true

record:
  check-interval: 25
  work-path: /bilirecord

logging:
  file:
    path: ${record.work-path}/log/
  logback:
    rollingpolicy:
      max-file-size: 50MB

