server:
  port: 80
  forward-headers-strategy: native


spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:retry:${record.work-path}/db
    username: sa
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  task:
    scheduling:
      pool:
        size: 10
  h2:
    console:
      enabled: true

record:
  check-interval: 25
  work-path: ${user.home}/.bili

logging:
  file:
    path: ${record.work-path}/log/
  logback:
    rollingpolicy:
      max-file-size: 50MB

