name: Build and Push Multi-Arch Docker Images

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  package-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update POM version
        run: sed -i "s|<version>0.0.1-SNAPSHOT</version>|<version>1.2.3</version>|g" pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Copy WAR File
        run: |
          ls -l target/
          cp target/*.war Docker/ROOT.war

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Release
        uses: softprops/action-gh-release@v1
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          tag_name: prebuild_driver
          name: Release ${{ github.sha }}
          body: 由提交${{ github.sha }}自动触发编译生成的Release。
          draft: false
          prerelease: false
          files: |
            target/*.war

  release-assets:
    needs: [ package-and-build ]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: target/*.war # 或者 target/*.jar 等，根据你的项目配置
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
