name: Build and Push Multi-Arch Docker Images

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  package-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Update POM version
        run: sed -i "s|<version>0.0.1-SNAPSHOT</version>|<version>1.2.3</version>|g" pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Copy WAR File
        run: |
          ls -l target/
          cp target/*.war Docker/ROOT.war

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - uses: actions/upload-artifact@v4
        with:
          name: agileconfig-ui
          path: target/*.war
